### ISSUE TITLE
特殊区域

### ISSUE THREAD

**Issue by souryou** [gaohuazi/china_regions#1]
没有“台湾” “钓鱼岛” 等特殊地区，放入生产环境不会出问题吗？比较敏感啊

**Comment by gaohuazi** [comment]
> 没有“台湾” “钓鱼岛” 等特殊地区，放入生产环境不会出问题吗？比较敏感啊

感谢，是有必要，最近抽空更新，目前国家统计局还没有详细的台湾等地区的数据

**Comment by gaohuazi** [comment]
已增加台湾、香港、澳门相关数据
