### ISSUE TITLE
可以考虑更新数据库字段长度吗

### ISSUE THREAD

**Issue by Chenjintao1997** [gaohuazi/china_regions#2]
![image](https://user-images.githubusercontent.com/37171474/96728979-3b685b00-13e7-11eb-9129-4c4f32d9a3fd.png)
这只是其中一个，id字段的长度也小也报了索引越界；
建议:
1.init.sql增加相关字段的长度
2.可以考虑把code相关的字段设为varchar吗

**Comment by Chenjintao1997** [comment]
![image](https://user-images.githubusercontent.com/37171474/96730913-42906880-13e9-11eb-8ad9-f5b24cc3e1ea.png)
这是我修改后的

**Comment by gaohuazi** [comment]
感谢指出，已经修改字段长度问题,code改为int(10)，int只占用4字节,varchar更长
